/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountsTable: typeof import('./src/components/Account/AccountsTable.vue')['default']
    AppHeader: typeof import('./src/components/SidePanel/AppHeader.vue')['default']
    AppTitle: typeof import('./src/components/SidePanel/AppTitle.vue')['default']
    AuthenticationRequired: typeof import('./src/components/AuthenticationRequired.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CheckOrX: typeof import('./src/components/visuals/CheckOrX.vue')['default']
    Column: typeof import('primevue/column')['default']
    Connection: typeof import('./src/components/Account/Connection.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FilterPanel: typeof import('./src/components/Search/FilterPanel/FilterPanel.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    LogOutButton: typeof import('./src/components/auth/LogOutButton.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Panel: typeof import('primevue/panel')['default']
    PanelHeader: typeof import('./src/components/SidePanel/PanelHeader.vue')['default']
    PannelHeader: typeof import('./src/components/SidePanel/PannelHeader.vue')['default']
    Password: typeof import('primevue/password')['default']
    Permissions: typeof import('./src/components/Account/Permissions.vue')['default']
    RegistrationCode: typeof import('./src/components/Account/RegistrationCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    SidePanel: typeof import('./src/components/SidePanel/SidePanel.vue')['default']
    SidePanelRouterLink: typeof import('./src/components/SidePanel/SidePanelRouterLink.vue')['default']
    SidePannelRouterLink: typeof import('./src/components/SidePanel/SidePannelRouterLink.vue')['default']
  }
}
